#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".
GIT_WORK_TREE=/var/www/html git checkout -f
echo "checkin at: <$date)> " >> /var/www/html/updates_log
#exec git update-server-info
